//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplikáció
{
    using System;
    using System.Collections.Generic;
    
    public partial class employeeAccount
    {
        public long user_id { get; set; }
        public string Name { get; set; }
        public string Mother_Name { get; set; }
        public string DOB { get; set; }
        public string Phone_No { get; set; }
        public Nullable<decimal> Zip_Code { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
