//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApplikáció
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD
    {
        public long sno { get; set; }
        public Nullable<decimal> Account_No { get; set; }
        public string Message { get; set; }
        public string Amount { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<decimal> Interest_Rate { get; set; }
        public string Maturity_Date { get; set; }
        public Nullable<decimal> Maturity_Amount { get; set; }
        public string Start_Date { get; set; }
    }
}
